name: Documentation Bug Report
description: Report a bug regarding the docs website
title: "[Docs-Bug]: "
labels: ["bug", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: browser
    attributes:
      label: Browser info
      description: Which browsers are you seeing the issue on?
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
