name: Release
on:
    push:
        branches:
            - main
jobs:
    release:
        runs-on: ubuntu-latest
        name: Release
        if: github.repository == 'pilcrowOnPaper/lucia-sveltekit'
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  registry-url: "https://registry.npmjs.org"
            - run: pnpm i
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
